modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="magicdevelopment"
version="1.0.0"
displayName="Aeydeebee76's Magic development"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="alexanderdbain, MCreator"

[[dependencies.magicdevelopment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




